# Generated by Django 5.1.1 on 2024-09-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_farmers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EMPLOYEE", "Employee"),
                    ("FARMER", "Farmer"),
                ],
                default="ADMIN",
                max_length=50,
            ),
        ),
    ]
