# Generated by Django 5.1.1 on 2024-10-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_employees"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employees",
        ),
        migrations.DeleteModel(
            name="Farmers",
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_management.user",),
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_management.user",),
        ),
    ]
