# Generated by Django 5.1.1 on 2024-10-01 03:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_delete_employees_delete_farmers_employee_farmer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_management.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Farmers",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_management.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EMPLOYEE", "Employee"),
                    ("FARMER", "Farmer"),
                ],
                max_length=50,
            ),
        ),
    ]
