# Generated by Django 5.1.1 on 2024-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("ext_name", models.CharField(blank=True, max_length=10, null=True)),
                ("house_no", models.CharField(default="", max_length=10)),
                ("street", models.CharField(default="", max_length=100)),
                ("baranggay", models.CharField(default="", max_length=100)),
                ("municipality", models.CharField(default="", max_length=100)),
                ("province", models.CharField(default="", max_length=100)),
                ("region", models.CharField(default="", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("pwd", models.BooleanField(default=False)),
                ("contact_no", models.CharField(max_length=15)),
                ("religion", models.CharField(default="", max_length=10)),
                (
                    "educ_attainment",
                    models.CharField(
                        choices=[
                            ("HS", "High School"),
                            ("UG", "Undergraduate"),
                            ("G", "Graduate"),
                        ],
                        default="HS",
                        max_length=10,
                    ),
                ),
                (
                    "civil_status",
                    models.CharField(
                        choices=[
                            ("S", "Single"),
                            ("M", "Married"),
                            ("D", "Divorced"),
                            ("W", "Widowed"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("day_of_birth", models.IntegerField(default=1)),
                ("month_of_birth", models.IntegerField(default=1)),
                ("year_of_birth", models.IntegerField(default=2000)),
                ("birthplace", models.CharField(default="", max_length=100)),
                (
                    "name_of_spouse",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mothers_maiden",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name_of_household_head",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("household_members", models.IntegerField(blank=True, null=True)),
                ("household_male", models.IntegerField(blank=True, null=True)),
                ("household_female", models.IntegerField(blank=True, null=True)),
                ("govern_id", models.CharField(blank=True, max_length=100, null=True)),
                ("id_type", models.CharField(blank=True, max_length=50, null=True)),
                ("id_no", models.CharField(blank=True, max_length=100, null=True)),
                ("is_member", models.BooleanField(default=False)),
                ("specify", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "if_emergency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "main_livelihood",
                    models.CharField(
                        choices=[
                            ("Farmer", "Farmer"),
                            ("Farmworkers", "Farmworkers"),
                            ("Fisherfolk", "Fisherfolk"),
                        ],
                        default="Farmer",
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "specify_position",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
